import 'package:flutter/material.dart';

class PrivacyScreen extends StatelessWidget {
  static const String routeName = "/privacy";

  static void navigateTo(BuildContext context) {
    Navigator.pushNamed(context, routeName);
  }

  const PrivacyScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Privacy Policy"),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Privacy Policy",
              style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            Text("Last updated: May 30, 2025"),
            SizedBox(height: 16),
            Text(
              "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure "
              "of Your information when You use the Service and tells You about Your privacy rights and how "
              "the law protects You.",
            ),
            SizedBox(height: 8),
            Text(
              "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the "
              "collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been "
              "created with the help of the TermsFeed Privacy Policy Generator.",
            ),
            SizedBox(height: 8),
            Text(
              "Interpretation and Definitions",
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            Text(
              "Interpretation\nThe words of which the initial letter is capitalized have meanings defined under the following conditions. "
              "The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
            ),
            SizedBox(height: 8),
            Text(
              "Definitions\nFor the purposes of this Privacy Policy:\n\n"
              "- Account means a unique account created for You to access our Service or parts of our Service.\n"
              "- Company (referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Doctodoc.\n"
              "- Personal Data is any information that relates to an identified or identifiable individual.\n"
              "- Service refers to the Application or the Website or both.\n"
              "- Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.\n"
              "- You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.",
            ),
            SizedBox(height: 8),
            Text(
              "Collecting and Using Your Personal Data",
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 8),
            Text(
              "Types of Data Collected\n\nPersonal Data\nWhile using Our Service, We may ask You to provide Us with certain personally identifiable information "
              "that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:\n\n"
              "- Email address\n- First name and last name\n- Usage Data",
            ),
            SizedBox(height: 8),
            Text(
              "Usage Data\nUsage Data is collected automatically when using the Service.\n\nUsage Data may include information such as Your Device's Internet Protocol address "
              "(e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, "
              "unique device identifiers and other",
            ),
            SizedBox(height: 8),
          ],
        ),
      ),
    );
  }
}
